spring:
  profiles:
    active:
  datasource:
    url: jdbc:mysql://localhost:3306/wht?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  ##静态资源访问
  resources:
    static-locations: classpath:/static/
    chain:
     strategy:
       content:
         enabled: true
         paths: /**
  ##配置thymeleaf
  thymeleaf:
    prefix: classpath:/templates
    suffix: html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

server:
  port: 8081
  servlet:
    context-path: /wht
#日志
#logging:
#  config: classpath:log4j2.xml

#mybatis Mapper文件
mybatis:
  mapper-locations: classpath:mapper/*.xml


# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10



